### ISSUE TITLE
FEATURE: Add new station Willy

### ISSUE THREAD

**Issue by larsfoll** [robinbakker/1tuner#1]
Suggestion to add a new radio station 'Willy'. 

Valid json for this:

` "willy": {
    "displayorder": 79,
    "genres": ["rock"],
    "language": "nl-be",
    "logosource": "https://profile-images.scdn.co/images/userprofile/default/641e289cc7fc1e0dff519fd9a92624bd36b76076",
    "name": "Willy",
    "streams": [
      {
        "mimetype": "audio/mp3",
        "url": "https://playerservices.streamtheworld.com/api/livestream-redirect/WILLY.mp3"
      }
    ],
    "website": "https://www.willy.radio/"
  }`

Great app btw, keep it up!

**Comment by robinbakker** [comment]
Thanks! I will add it, I'm working on the last couple of changes for the next big update, and Willy will be added as well then! 👍

**Comment by larsfoll** [comment]
Great news, thanks!

**Comment by robinbakker** [comment]
Done 😃
https://1tuner.com/radio-station/willy
